-- Fase 6.2 - Sync batches
-- Objetivo:
-- Registrar cada subida/descarga masiva de sincronización offline-first.
--
-- Modelo:
-- app_devices = instalación/dispositivo
-- sync_batches = intento/lote de sincronización
-- sync_mutations = cambios individuales dentro del lote, próxima fase

begin;

-- =========================================================
-- SYNC BATCHES
-- =========================================================

create table if not exists public.sync_batches (
  id uuid primary key default extensions.gen_random_uuid(),

  business_id uuid not null references public.businesses(id) on delete restrict,
  app_device_id uuid not null references public.app_devices(id) on delete restrict,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  branch_id uuid references public.branches(id) on delete set null,

  client_batch_id text not null,

  direction text not null default 'upload',
  status text not null default 'pending',

  mutation_count integer not null default 0,
  applied_count integer not null default 0,
  skipped_count integer not null default 0,
  conflict_count integer not null default 0,
  error_count integer not null default 0,

  client_started_at timestamp without time zone,
  client_completed_at timestamp without time zone,

  server_started_at timestamp without time zone default now(),
  server_completed_at timestamp without time zone,

  error_message text,

  checksum text,

  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  deleted_at timestamp without time zone,

  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  deleted_by uuid references public.profiles(id) on delete set null,
  delete_reason text,

  version integer not null default 1,
  sync_status text not null default 'synced',
  metadata jsonb not null default '{}'::jsonb,

  constraint sync_batches_client_batch_id_not_blank
    check (length(trim(client_batch_id)) > 0),

  constraint sync_batches_direction_check
    check (direction in ('upload', 'download', 'bidirectional')),

  constraint sync_batches_status_check
    check (
      status in (
        'pending',
        'processing',
        'completed',
        'partial',
        'failed',
        'cancelled'
      )
    ),

  constraint sync_batches_counts_non_negative
    check (
      mutation_count >= 0
      and applied_count >= 0
      and skipped_count >= 0
      and conflict_count >= 0
      and error_count >= 0
    ),

  constraint sync_batches_processed_lte_total
    check (
      applied_count + skipped_count + conflict_count + error_count <= mutation_count
    ),

  constraint sync_batches_client_times_order
    check (
      client_started_at is null
      or client_completed_at is null
      or client_completed_at >= client_started_at
    ),

  constraint sync_batches_server_times_order
    check (
      server_started_at is null
      or server_completed_at is null
      or server_completed_at >= server_started_at
    ),

  constraint sync_batches_completed_requires_server_completed_at
    check (
      status not in ('completed', 'partial', 'failed', 'cancelled')
      or server_completed_at is not null
    ),

  constraint sync_batches_version_positive
    check (version >= 1),

  constraint sync_batches_sync_status_check
    check (sync_status in ('synced', 'pending', 'conflict', 'error'))
);

comment on table public.sync_batches
is 'Offline-first synchronization batches sent by app devices.';

comment on column public.sync_batches.client_batch_id
is 'Stable local batch identifier generated by the app/device.';

comment on column public.sync_batches.direction
is 'Sync direction: upload, download or bidirectional.';

comment on column public.sync_batches.status
is 'Lifecycle of the sync batch.';

comment on column public.sync_batches.mutation_count
is 'Number of mutations included in this batch.';

comment on column public.sync_batches.checksum
is 'Optional checksum/hash of the batch payload for integrity checks.';

-- =========================================================
-- ÍNDICES
-- =========================================================

create unique index if not exists sync_batches_business_device_client_batch_unique
on public.sync_batches (business_id, app_device_id, client_batch_id)
where deleted_at is null;

create index if not exists sync_batches_business_status_idx
on public.sync_batches (business_id, status, server_started_at desc)
where deleted_at is null;

create index if not exists sync_batches_device_started_idx
on public.sync_batches (app_device_id, server_started_at desc)
where deleted_at is null;

create index if not exists sync_batches_profile_started_idx
on public.sync_batches (business_id, profile_id, server_started_at desc)
where deleted_at is null;

create index if not exists sync_batches_branch_started_idx
on public.sync_batches (business_id, branch_id, server_started_at desc)
where deleted_at is null
  and branch_id is not null;

-- =========================================================
-- VALIDAR DEVICE / BUSINESS / PROFILE
-- =========================================================

create or replace function private.validate_sync_batch_device_consistency()
returns trigger
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_device record;
begin
  select
    ad.business_id,
    ad.profile_id,
    ad.branch_id,
    ad.status,
    ad.deleted_at
  into v_device
  from public.app_devices ad
  where ad.id = new.app_device_id;

  if v_device.business_id is null then
    raise exception 'sync_batches.app_device_id must reference an existing app_device';
  end if;

  if v_device.deleted_at is not null then
    raise exception 'Cannot create sync batch for deleted app_device';
  end if;

  if v_device.status <> 'active' then
    raise exception 'Cannot create sync batch for inactive or blocked app_device';
  end if;

  if new.business_id <> v_device.business_id then
    raise exception 'sync_batches.business_id must match app_devices.business_id';
  end if;

  if new.profile_id <> v_device.profile_id then
    raise exception 'sync_batches.profile_id must match app_devices.profile_id';
  end if;

  if new.branch_id is not null then
    if not exists (
      select 1
      from public.branches br
      where br.id = new.branch_id
        and br.business_id = new.business_id
        and br.deleted_at is null
        and br.status = 'active'
    ) then
      raise exception 'sync_batches.branch_id must belong to the same active business';
    end if;
  end if;

  if v_device.branch_id is not null
     and new.branch_id is not null
     and new.branch_id <> v_device.branch_id then
    raise exception 'sync_batches.branch_id must match app_devices.branch_id when device is branch-scoped';
  end if;

  return new;
end;
$$;

comment on function private.validate_sync_batch_device_consistency()
is 'Ensures sync_batches match app_devices business/profile and optional branch scope.';

drop trigger if exists trg_sync_batches_validate_device_consistency
on public.sync_batches;

create trigger trg_sync_batches_validate_device_consistency
before insert or update of business_id, app_device_id, profile_id, branch_id
on public.sync_batches
for each row
execute function private.validate_sync_batch_device_consistency();

-- =========================================================
-- FILL DEFAULTS
-- =========================================================

create or replace function private.fill_sync_batch_defaults()
returns trigger
language plpgsql
security definer
set search_path = public, private, extensions
as $$
begin
  new.created_by := coalesce(new.created_by, auth.uid());
  new.updated_by := coalesce(new.updated_by, auth.uid());

  if new.server_started_at is null then
    new.server_started_at := now();
  end if;

  if new.status in ('completed', 'partial', 'failed', 'cancelled')
     and new.server_completed_at is null then
    new.server_completed_at := now();
  end if;

  return new;
end;
$$;

comment on function private.fill_sync_batch_defaults()
is 'Fills audit and server timestamps for sync_batches.';

drop trigger if exists trg_sync_batches_fill_defaults
on public.sync_batches;

create trigger trg_sync_batches_fill_defaults
before insert or update of status
on public.sync_batches
for each row
execute function private.fill_sync_batch_defaults();

-- =========================================================
-- updated_at y version
-- =========================================================

drop trigger if exists trg_sync_batches_updated_at
on public.sync_batches;

create trigger trg_sync_batches_updated_at
before update on public.sync_batches
for each row
execute function public.update_updated_at_column();

drop trigger if exists trg_sync_batches_increment_version
on public.sync_batches;

create trigger trg_sync_batches_increment_version
before update on public.sync_batches
for each row
execute function public.increment_row_version_on_business_change();

-- =========================================================
-- RLS
-- =========================================================

alter table public.sync_batches enable row level security;

drop policy if exists sync_batches_select_allowed on public.sync_batches;
drop policy if exists sync_batches_insert_own_allowed on public.sync_batches;
drop policy if exists sync_batches_update_own_allowed on public.sync_batches;
drop policy if exists sync_batches_admin_update_allowed on public.sync_batches;
drop policy if exists sync_batches_delete_blocked on public.sync_batches;

-- Usuarios ven sus propios batches.
-- Admin/settings/security puede ver batches del negocio.
create policy sync_batches_select_allowed
on public.sync_batches
for select
to authenticated
using (
  deleted_at is null
  and business_id is not null
  and (
    profile_id = auth.uid()
    or private.has_business_permission(business_id, 'settings.business')
    or private.has_business_permission(business_id, 'security_events.read')
  )
);

-- El usuario puede crear batches de su propio dispositivo.
create policy sync_batches_insert_own_allowed
on public.sync_batches
for insert
to authenticated
with check (
  deleted_at is null
  and profile_id = auth.uid()
  and private.is_business_member(business_id)
  and (
    branch_id is null
    or private.has_branch_access(business_id, branch_id)
  )
  and exists (
    select 1
    from public.app_devices ad
    where ad.id = sync_batches.app_device_id
      and ad.business_id = sync_batches.business_id
      and ad.profile_id = auth.uid()
      and ad.status = 'active'
      and ad.deleted_at is null
  )
);

-- El usuario puede actualizar su propio batch mientras no esté finalizado.
create policy sync_batches_update_own_allowed
on public.sync_batches
for update
to authenticated
using (
  deleted_at is null
  and profile_id = auth.uid()
  and private.is_business_member(business_id)
  and status in ('pending', 'processing')
)
with check (
  profile_id = auth.uid()
  and private.is_business_member(business_id)
);

-- Admin/settings puede actualizar batches del negocio.
create policy sync_batches_admin_update_allowed
on public.sync_batches
for update
to authenticated
using (
  deleted_at is null
  and (
    private.has_business_permission(business_id, 'settings.business')
    or private.has_business_permission(business_id, 'security_events.read')
  )
)
with check (
  private.has_business_permission(business_id, 'settings.business')
  or private.has_business_permission(business_id, 'security_events.read')
);

-- No hard delete.
create policy sync_batches_delete_blocked
on public.sync_batches
for delete
to authenticated
using (false);

commit;