-- Fase 6.1 - Sync app devices
-- Objetivo:
-- Registrar instalaciones/dispositivos offline-first de la app.
--
-- Nota:
-- Esta tabla representa dispositivos de sincronización, no activos/equipos del negocio.
-- Para activos/equipos ya existe public.devices.

begin;

-- =========================================================
-- APP DEVICES
-- =========================================================

create table if not exists public.app_devices (
  id uuid primary key default extensions.gen_random_uuid(),

  business_id uuid not null references public.businesses(id) on delete restrict,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  branch_id uuid references public.branches(id) on delete set null,

  installation_id text not null,
  device_name text,
  platform text not null default 'unknown',

  app_version text,
  os_version text,

  status text not null default 'active',

  last_seen_at timestamp without time zone,
  last_sync_started_at timestamp without time zone,
  last_sync_completed_at timestamp without time zone,

  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  deleted_at timestamp without time zone,

  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  deleted_by uuid references public.profiles(id) on delete set null,
  delete_reason text,

  version integer not null default 1,
  sync_status text not null default 'synced',
  metadata jsonb not null default '{}'::jsonb,

  constraint app_devices_installation_id_not_blank
    check (length(trim(installation_id)) > 0),

  constraint app_devices_platform_check
    check (
      platform in (
        'android',
        'ios',
        'windows',
        'macos',
        'linux',
        'web',
        'unknown'
      )
    ),

  constraint app_devices_status_check
    check (
      status in (
        'active',
        'inactive',
        'blocked'
      )
    ),

  constraint app_devices_version_positive
    check (version >= 1),

  constraint app_devices_sync_status_check
    check (sync_status in ('synced', 'pending', 'conflict', 'error')),

  constraint app_devices_sync_times_order
    check (
      last_sync_started_at is null
      or last_sync_completed_at is null
      or last_sync_completed_at >= last_sync_started_at
    )
);

comment on table public.app_devices
is 'Offline-first app installations/devices allowed to sync data with Supabase.';

comment on column public.app_devices.installation_id
is 'Stable local installation identifier generated by the app.';

comment on column public.app_devices.branch_id
is 'Optional default branch used by this app device.';

comment on column public.app_devices.last_sync_started_at
is 'Last time this app device started a sync process.';

comment on column public.app_devices.last_sync_completed_at
is 'Last time this app device completed a sync process successfully.';

-- =========================================================
-- ÍNDICES
-- =========================================================

create unique index if not exists app_devices_business_installation_active_unique
on public.app_devices (business_id, installation_id)
where deleted_at is null;

create index if not exists app_devices_business_profile_idx
on public.app_devices (business_id, profile_id)
where deleted_at is null;

create index if not exists app_devices_business_branch_idx
on public.app_devices (business_id, branch_id)
where deleted_at is null
  and branch_id is not null;

create index if not exists app_devices_last_sync_idx
on public.app_devices (business_id, last_sync_completed_at desc)
where deleted_at is null;

-- =========================================================
-- VALIDAR BUSINESS MEMBERSHIP
-- =========================================================

create or replace function private.validate_app_device_membership()
returns trigger
language plpgsql
security definer
set search_path = public, private, extensions
as $$
begin
  if not exists (
    select 1
    from public.business_members bm
    where bm.business_id = new.business_id
      and bm.profile_id = new.profile_id
      and bm.status = 'active'
      and bm.deleted_at is null
  ) then
    raise exception 'app_devices.profile_id must be an active member of business_id';
  end if;

  return new;
end;
$$;

comment on function private.validate_app_device_membership()
is 'Ensures app_devices.profile_id is an active member of the business.';

drop trigger if exists trg_app_devices_validate_membership
on public.app_devices;

create trigger trg_app_devices_validate_membership
before insert or update of business_id, profile_id
on public.app_devices
for each row
execute function private.validate_app_device_membership();

-- =========================================================
-- VALIDAR BRANCH/BUSINESS
-- =========================================================

create or replace function private.validate_app_device_branch_consistency()
returns trigger
language plpgsql
security definer
set search_path = public, private, extensions
as $$
begin
  if new.branch_id is not null then
    if not exists (
      select 1
      from public.branches br
      where br.id = new.branch_id
        and br.business_id = new.business_id
        and br.deleted_at is null
        and br.status = 'active'
    ) then
      raise exception 'app_devices.branch_id must belong to the same active business';
    end if;
  end if;

  return new;
end;
$$;

comment on function private.validate_app_device_branch_consistency()
is 'Ensures app_devices.branch_id belongs to the same business_id.';

drop trigger if exists trg_app_devices_validate_branch_consistency
on public.app_devices;

create trigger trg_app_devices_validate_branch_consistency
before insert or update of business_id, branch_id
on public.app_devices
for each row
execute function private.validate_app_device_branch_consistency();

-- =========================================================
-- updated_at y version
-- =========================================================

drop trigger if exists trg_app_devices_updated_at
on public.app_devices;

create trigger trg_app_devices_updated_at
before update on public.app_devices
for each row
execute function public.update_updated_at_column();

drop trigger if exists trg_app_devices_increment_version
on public.app_devices;

create trigger trg_app_devices_increment_version
before update on public.app_devices
for each row
execute function public.increment_row_version_on_business_change();

-- =========================================================
-- RLS
-- =========================================================

alter table public.app_devices enable row level security;

drop policy if exists app_devices_select_allowed on public.app_devices;
drop policy if exists app_devices_insert_own_allowed on public.app_devices;
drop policy if exists app_devices_update_own_allowed on public.app_devices;
drop policy if exists app_devices_admin_update_allowed on public.app_devices;
drop policy if exists app_devices_delete_blocked on public.app_devices;

-- El usuario puede ver sus propios dispositivos.
-- Admin/settings puede ver dispositivos del negocio.
create policy app_devices_select_allowed
on public.app_devices
for select
to authenticated
using (
  deleted_at is null
  and business_id is not null
  and (
    profile_id = auth.uid()
    or private.has_business_permission(business_id, 'settings.business')
    or private.has_business_permission(business_id, 'security_events.read')
  )
);

-- El usuario puede registrar su propio dispositivo si es miembro activo del negocio.
create policy app_devices_insert_own_allowed
on public.app_devices
for insert
to authenticated
with check (
  deleted_at is null
  and profile_id = auth.uid()
  and private.is_business_member(business_id)
  and (
    branch_id is null
    or private.has_branch_access(business_id, branch_id)
  )
);

-- El usuario puede actualizar su propio dispositivo.
create policy app_devices_update_own_allowed
on public.app_devices
for update
to authenticated
using (
  deleted_at is null
  and profile_id = auth.uid()
  and private.is_business_member(business_id)
)
with check (
  profile_id = auth.uid()
  and private.is_business_member(business_id)
  and (
    branch_id is null
    or private.has_branch_access(business_id, branch_id)
  )
);

-- Admin/settings puede bloquear o editar dispositivos del negocio.
create policy app_devices_admin_update_allowed
on public.app_devices
for update
to authenticated
using (
  deleted_at is null
  and (
    private.has_business_permission(business_id, 'settings.business')
    or private.has_business_permission(business_id, 'security_events.read')
  )
)
with check (
  private.has_business_permission(business_id, 'settings.business')
  or private.has_business_permission(business_id, 'security_events.read')
);

-- No hard delete.
create policy app_devices_delete_blocked
on public.app_devices
for delete
to authenticated
using (false);

commit;