-- Fase 6.3 - Sync mutations
-- Objetivo:
-- Registrar cambios individuales hechos offline por la app.
--
-- sync_batches = lote de sincronización
-- sync_mutations = cada cambio local dentro del lote
--
-- Nota:
-- Esta tabla todavía no procesa/aplica cambios automáticamente.
-- La RPC process_sync_batch() vendrá después.

begin;

-- =========================================================
-- SYNC MUTATIONS
-- =========================================================

create table if not exists public.sync_mutations (
  id uuid primary key default extensions.gen_random_uuid(),

  business_id uuid not null references public.businesses(id) on delete restrict,
  sync_batch_id uuid not null references public.sync_batches(id) on delete cascade,
  app_device_id uuid not null references public.app_devices(id) on delete restrict,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  branch_id uuid references public.branches(id) on delete set null,

  client_mutation_id text not null,
  client_sequence integer not null,

  entity_table text not null,
  entity_id uuid not null,

  operation text not null,

  payload jsonb not null default '{}'::jsonb,
  before_payload jsonb,
  changed_fields text[],

  base_version integer,
  base_updated_at timestamp without time zone,

  status text not null default 'pending',

  server_processed_at timestamp without time zone,
  server_entity_version integer,

  error_code text,
  error_message text,

  idempotency_key text,

  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now(),
  deleted_at timestamp without time zone,

  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  deleted_by uuid references public.profiles(id) on delete set null,
  delete_reason text,

  version integer not null default 1,
  sync_status text not null default 'synced',
  metadata jsonb not null default '{}'::jsonb,

  constraint sync_mutations_client_mutation_id_not_blank
    check (length(trim(client_mutation_id)) > 0),

  constraint sync_mutations_client_sequence_non_negative
    check (client_sequence >= 0),

  constraint sync_mutations_entity_table_not_blank
    check (length(trim(entity_table)) > 0),

  constraint sync_mutations_entity_table_allowed
    check (
      entity_table in (
        'categories',
        'products',
        'customers',
        'suppliers',

        'purchases',
        'purchase_items',

        'sales',
        'sale_items',
        'sale_payments',

        'inventory_movements',
        'stock_counts',
        'stock_count_items',
        'inventory_transfers',
        'inventory_transfer_items',

        'cash_sessions',
        'cash_registers'
      )
    ),

  constraint sync_mutations_operation_check
    check (
      operation in (
        'insert',
        'update',
        'upsert',
        'soft_delete',
        'delete'
      )
    ),

  constraint sync_mutations_status_check
    check (
      status in (
        'pending',
        'processing',
        'applied',
        'skipped',
        'conflict',
        'error'
      )
    ),

  constraint sync_mutations_payload_object_check
    check (jsonb_typeof(payload) = 'object'),

  constraint sync_mutations_before_payload_object_check
    check (
      before_payload is null
      or jsonb_typeof(before_payload) = 'object'
    ),

  constraint sync_mutations_base_version_positive
    check (
      base_version is null
      or base_version >= 1
    ),

  constraint sync_mutations_server_entity_version_positive
    check (
      server_entity_version is null
      or server_entity_version >= 1
    ),

  constraint sync_mutations_processed_requires_timestamp
    check (
      status in ('pending', 'processing')
      or server_processed_at is not null
    ),

  constraint sync_mutations_error_requires_message
    check (
      status <> 'error'
      or error_message is not null
    ),

  constraint sync_mutations_conflict_requires_message
    check (
      status <> 'conflict'
      or error_message is not null
    ),

  constraint sync_mutations_version_positive
    check (version >= 1),

  constraint sync_mutations_sync_status_check
    check (sync_status in ('synced', 'pending', 'conflict', 'error'))
);

comment on table public.sync_mutations
is 'Individual offline-first mutations uploaded by app devices as part of sync batches.';

comment on column public.sync_mutations.client_mutation_id
is 'Stable local mutation identifier generated by the app/device.';

comment on column public.sync_mutations.client_sequence
is 'Local sequence number used to preserve mutation order inside a batch.';

comment on column public.sync_mutations.entity_table
is 'Target logical table/entity affected by this mutation.';

comment on column public.sync_mutations.entity_id
is 'UUID of the affected entity. For offline-first inserts, the app should generate this ID locally.';

comment on column public.sync_mutations.operation
is 'Mutation operation: insert, update, upsert, soft_delete or delete.';

comment on column public.sync_mutations.payload
is 'New data or patch sent by the client.';

comment on column public.sync_mutations.before_payload
is 'Optional client-side previous data snapshot for conflict detection.';

comment on column public.sync_mutations.base_version
is 'Entity version known by the client when the mutation was created.';

comment on column public.sync_mutations.base_updated_at
is 'Entity updated_at known by the client when the mutation was created.';

comment on column public.sync_mutations.idempotency_key
is 'Optional idempotency key for safe retries.';

-- =========================================================
-- ÍNDICES
-- =========================================================

create unique index if not exists sync_mutations_business_device_client_mutation_unique
on public.sync_mutations (business_id, app_device_id, client_mutation_id)
where deleted_at is null;

create unique index if not exists sync_mutations_batch_sequence_unique
on public.sync_mutations (sync_batch_id, client_sequence)
where deleted_at is null;

create unique index if not exists sync_mutations_idempotency_key_unique
on public.sync_mutations (business_id, idempotency_key)
where idempotency_key is not null
  and deleted_at is null;

create index if not exists sync_mutations_batch_status_idx
on public.sync_mutations (sync_batch_id, status, client_sequence)
where deleted_at is null;

create index if not exists sync_mutations_business_status_idx
on public.sync_mutations (business_id, status, created_at desc)
where deleted_at is null;

create index if not exists sync_mutations_entity_idx
on public.sync_mutations (business_id, entity_table, entity_id)
where deleted_at is null;

create index if not exists sync_mutations_device_sequence_idx
on public.sync_mutations (app_device_id, client_sequence)
where deleted_at is null;

-- =========================================================
-- VALIDAR BATCH / DEVICE / PROFILE
-- =========================================================

create or replace function private.validate_sync_mutation_batch_consistency()
returns trigger
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_batch record;
begin
  select
    sb.id,
    sb.business_id,
    sb.app_device_id,
    sb.profile_id,
    sb.branch_id,
    sb.status,
    sb.deleted_at
  into v_batch
  from public.sync_batches sb
  where sb.id = new.sync_batch_id;

  if v_batch.id is null then
    raise exception 'sync_mutations.sync_batch_id must reference an existing sync_batch';
  end if;

  if v_batch.deleted_at is not null then
    raise exception 'Cannot add mutation to deleted sync_batch';
  end if;

  if v_batch.status not in ('pending', 'processing') then
    raise exception 'Cannot add mutation to finalized sync_batch';
  end if;

  if new.business_id <> v_batch.business_id then
    raise exception 'sync_mutations.business_id must match sync_batches.business_id';
  end if;

  if new.app_device_id <> v_batch.app_device_id then
    raise exception 'sync_mutations.app_device_id must match sync_batches.app_device_id';
  end if;

  if new.profile_id <> v_batch.profile_id then
    raise exception 'sync_mutations.profile_id must match sync_batches.profile_id';
  end if;

  if v_batch.branch_id is not null then
    if new.branch_id is null or new.branch_id <> v_batch.branch_id then
      raise exception 'sync_mutations.branch_id must match sync_batches.branch_id when batch is branch-scoped';
    end if;
  end if;

  if new.branch_id is not null then
    if not exists (
      select 1
      from public.branches br
      where br.id = new.branch_id
        and br.business_id = new.business_id
        and br.deleted_at is null
        and br.status = 'active'
    ) then
      raise exception 'sync_mutations.branch_id must belong to the same active business';
    end if;
  end if;

  return new;
end;
$$;

comment on function private.validate_sync_mutation_batch_consistency()
is 'Ensures sync mutations match their parent sync batch and branch scope.';

drop trigger if exists trg_sync_mutations_validate_batch_consistency
on public.sync_mutations;

create trigger trg_sync_mutations_validate_batch_consistency
before insert or update of business_id, sync_batch_id, app_device_id, profile_id, branch_id
on public.sync_mutations
for each row
execute function private.validate_sync_mutation_batch_consistency();

-- =========================================================
-- FILL DEFAULTS
-- =========================================================

create or replace function private.fill_sync_mutation_defaults()
returns trigger
language plpgsql
security definer
set search_path = public, private, extensions
as $$
begin
  new.created_by := coalesce(new.created_by, auth.uid());
  new.updated_by := coalesce(new.updated_by, auth.uid());

  if new.idempotency_key is null then
    new.idempotency_key :=
      new.app_device_id::text || ':' || new.client_mutation_id;
  end if;

  if new.status in ('applied', 'skipped', 'conflict', 'error')
     and new.server_processed_at is null then
    new.server_processed_at := now();
  end if;

  return new;
end;
$$;

comment on function private.fill_sync_mutation_defaults()
is 'Fills audit fields, default idempotency key and processed timestamp for sync_mutations.';

drop trigger if exists trg_sync_mutations_fill_defaults
on public.sync_mutations;

create trigger trg_sync_mutations_fill_defaults
before insert or update of status
on public.sync_mutations
for each row
execute function private.fill_sync_mutation_defaults();

-- =========================================================
-- ACTUALIZAR mutation_count DEL BATCH
-- =========================================================

create or replace function private.increment_sync_batch_mutation_count()
returns trigger
language plpgsql
security definer
set search_path = public, private, extensions
as $$
begin
  if new.deleted_at is null then
    update public.sync_batches sb
    set
      mutation_count = mutation_count + 1,
      updated_at = now()
    where sb.id = new.sync_batch_id;
  end if;

  return new;
end;
$$;

comment on function private.increment_sync_batch_mutation_count()
is 'Increments sync_batches.mutation_count when a mutation is added.';

drop trigger if exists trg_sync_mutations_increment_batch_count
on public.sync_mutations;

create trigger trg_sync_mutations_increment_batch_count
after insert
on public.sync_mutations
for each row
execute function private.increment_sync_batch_mutation_count();

-- =========================================================
-- updated_at y version
-- =========================================================

drop trigger if exists trg_sync_mutations_updated_at
on public.sync_mutations;

create trigger trg_sync_mutations_updated_at
before update on public.sync_mutations
for each row
execute function public.update_updated_at_column();

drop trigger if exists trg_sync_mutations_increment_version
on public.sync_mutations;

create trigger trg_sync_mutations_increment_version
before update on public.sync_mutations
for each row
execute function public.increment_row_version_on_business_change();

-- =========================================================
-- RLS
-- =========================================================

alter table public.sync_mutations enable row level security;

drop policy if exists sync_mutations_select_allowed on public.sync_mutations;
drop policy if exists sync_mutations_insert_own_allowed on public.sync_mutations;
drop policy if exists sync_mutations_update_own_pending_allowed on public.sync_mutations;
drop policy if exists sync_mutations_admin_update_allowed on public.sync_mutations;
drop policy if exists sync_mutations_delete_blocked on public.sync_mutations;

-- Usuario ve sus propias mutaciones.
-- Admin/settings/security puede auditar las mutaciones del negocio.
create policy sync_mutations_select_allowed
on public.sync_mutations
for select
to authenticated
using (
  deleted_at is null
  and business_id is not null
  and (
    profile_id = auth.uid()
    or private.has_business_permission(business_id, 'settings.business')
    or private.has_business_permission(business_id, 'security_events.read')
  )
);

-- Usuario puede insertar mutaciones en sus propios batches activos.
create policy sync_mutations_insert_own_allowed
on public.sync_mutations
for insert
to authenticated
with check (
  deleted_at is null
  and profile_id = auth.uid()
  and private.is_business_member(business_id)
  and exists (
    select 1
    from public.sync_batches sb
    where sb.id = sync_mutations.sync_batch_id
      and sb.business_id = sync_mutations.business_id
      and sb.app_device_id = sync_mutations.app_device_id
      and sb.profile_id = auth.uid()
      and sb.status in ('pending', 'processing')
      and sb.deleted_at is null
  )
  and exists (
    select 1
    from public.app_devices ad
    where ad.id = sync_mutations.app_device_id
      and ad.business_id = sync_mutations.business_id
      and ad.profile_id = auth.uid()
      and ad.status = 'active'
      and ad.deleted_at is null
  )
);

-- Usuario puede ajustar una mutación propia solo antes de ser procesada.
create policy sync_mutations_update_own_pending_allowed
on public.sync_mutations
for update
to authenticated
using (
  deleted_at is null
  and profile_id = auth.uid()
  and private.is_business_member(business_id)
  and status in ('pending', 'processing')
)
with check (
  profile_id = auth.uid()
  and private.is_business_member(business_id)
);

-- Admin/settings/security puede actualizar estado para auditoría/soporte.
create policy sync_mutations_admin_update_allowed
on public.sync_mutations
for update
to authenticated
using (
  deleted_at is null
  and (
    private.has_business_permission(business_id, 'settings.business')
    or private.has_business_permission(business_id, 'security_events.read')
  )
)
with check (
  private.has_business_permission(business_id, 'settings.business')
  or private.has_business_permission(business_id, 'security_events.read')
);

-- No hard delete.
create policy sync_mutations_delete_blocked
on public.sync_mutations
for delete
to authenticated
using (false);

commit;